CREATE TABLE Usuario (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(128) NOT NULL,
  Email VARCHAR(256) NULL,
  Login VARCHAR(64) NULL,
  Senha VARCHAR(64) NULL,
  Tipo CHAR(1) NOT NULL DEFAULT 'U',
  CONSTRAINT Usuario PRIMARY KEY(ID)
) ENGINE=MyISAM;


CREATE TABLE Acesso (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  IDUsuario INT UNSIGNED NOT NULL,
  DataLogin TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DataLogoff DATETIME NULL,
  CONSTRAINT Acesso PRIMARY KEY(ID),
  CONSTRAINT FK_Acesso_01 FOREIGN KEY (IDUsuario) REFERENCES Usuario(ID)
) ENGINE=MyISAM;


CREATE TABLE Local (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  Descricao VARCHAR(128) NOT NULL,
  CONSTRAINT Local PRIMARY KEY(ID)
) ENGINE=MyISAM;


CREATE TABLE Partida (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  IDLocal INT UNSIGNED NOT NULL,
  Data DATETIME NOT NULL,
  ValorBuyIn DECIMAL(10,2) NOT NULL,
  ValorReBuy DECIMAL(10,2) NOT NULL,
  FichasBuyIn INT UNSIGNED NOT NULL,
  FichasReBuy INT UNSIGNED NOT NULL,
  CONSTRAINT Partida PRIMARY KEY(ID),
  CONSTRAINT FK_Partida_01 FOREIGN KEY (IDLocal) REFERENCES Local(ID)
) ENGINE=MyISAM;


CREATE TABLE Participante (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  IDPartida INT UNSIGNED NOT NULL,
  IDUsuario INT UNSIGNED NOT NULL,
  ReBuys INT UNSIGNED NOT NULL DEFAULT 0,
  Vencedor TINYINT UNSIGNED NOT NULL DEFAULT 0,
  Fichas INT UNSIGNED NOT NULL DEFAULT 0,
  CONSTRAINT Participante PRIMARY KEY(ID),
  CONSTRAINT UK_Participante_01 UNIQUE KEY(IDPartida, IDUsuario),
  CONSTRAINT FK_Participante_01 FOREIGN KEY (IDPartida) REFERENCES Partida(ID),
  CONSTRAINT FK_Participante_02 FOREIGN KEY (IDUsuario) REFERENCES Usuario(ID)
) ENGINE=MyISAM;

CREATE TABLE Log (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	Data TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Responsavel VARCHAR(128) NOT NULL,
	Acao INT UNSIGNED NOT NULL,
	Local VARCHAR(128) NOT NULL,
	Campo VARCHAR(128) NULL,
	De VARCHAR(512) NULL,
	Para VARCHAR(512) NULL,
	CONSTRAINT Log PRIMARY KEY(ID)
) ENGINE=MyISAM;